# debug = False
# log_file =
# port = 80
# workers = 
# use_cdn = False
data_path = 'etc'

[openstack]
# domain_name = Default
# expires_time = 3600
# api_version = 
# cinder_api_version = v2
# fetch_max_version = true
