name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取项目代码
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 安装vue项目依赖
      run: |
        cd skylight-web
        sudo apt-get install -y npm nodejs
        # sudo npm install -g @vue/cli @vue/cli-service @vue/cli-plugin-babel > /dev/null
        sudo npm install > /dev/null

    - name: 构建vue项目
      run: |
        cd skylight-web
        sudo npm run build

    - name: 安装 Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"

    - name: 安装python项目依赖
      run: |
        sudo apt-get install -y gettext python3-pip python3-bs4 git > /dev/null
        python3 -m pip install -r requirements.txt > /dev/null

    - name: 构建python项目
      run: |
        python3 -m pip wheel --prefer-binary --no-deps --wheel-dir=dist ./

    - name: 登录阿里云镜像仓库
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALI_DOCKER_USERNAME }}
        password: ${{ secrets.ALI_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com

    - name: 构建并推送镜像
      run: |
        export PYTHONPATH=./
        export WHEEL=$(ls dist/skylight-*.whl |tail -n1)
        python3 install/build.py ${WHEEL} --push-as-latest -r registry.cn-hangzhou.aliyuncs.com/fjboy-ec -d
