name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install requirements
      run: |
        sudo apt-get install -y gettext python3-pip python3-bs4 git
        python3 -m pip install -r requirements.txt

    - name: Build Python Bdist Wheel
      run: |
        python3 -m pip wheel --prefer-binary --no-deps --wheel-dir=dist ./

    - name: Log in to ali docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.ALI_DOCKER_USERNAME }}
        password: ${{ secrets.ALI_DOCKER_PASSWORD }}
        registry: registry.cn-hangzhou.aliyuncs.com

    - name: Build & Push the Docker image
      run: |
        export PYTHONPATH=./
        export WHEEL=$(ls dist/vstackboard-*.whl |tail -n1)
        python3 install/build.py ${WHEEL} -lr registry.cn-hangzhou.aliyuncs.com/fjboy-ec
